export const TEST_PIZZAS = [
  {
    id: 0,
    name: 'Focaccia',
    ingredients: 'Bread with italian olive oil and rosemary',
    price: 6,
    photoName: 'pizzas/focaccia.jpg',
    category: 'veggie',
    image: '/img/focaccia.jpg',
  },
  {
    id: 1,
    name: 'Pizza Margherita',
    ingredients: 'Tomato and mozarella',
    price: 10,
    photoName: 'pizzas/margherita.jpg',
    category: 'veggie',
    image: '/img/margherita.jpg',
  },
  {
    id: 2,
    name: 'Pizza Spinaci',
    ingredients: 'Tomato, mozarella, spinach, and ricotta cheese',
    price: 12,
    photoName: 'pizzas/spinaci.jpg',
    category: 'veggie',
    image: '/img/spinaci.jpg',
  },
  {
    id: 3,
    name: 'Pizza Funghi',
    ingredients: 'Tomato, mozarella, mushrooms, and onion',
    price: 12,
    photoName: 'pizzas/funghi.jpg',
    category: 'veggie',
    image: '/img/funghi.jpg',
  },
  {
    id: 4,
    name: 'Pizza Salamino',
    ingredients: 'Tomato, mozarella, and pepperoni',
    price: 15,
    photoName: 'pizzas/salamino.jpg',
    category: 'meat',
    image: '/img/salamino.jpg',
  },
  {
    id: 5,
    name: 'Pizza Prosciutto',
    ingredients: 'Tomato, mozarella, ham, aragula, and burrata cheese',
    price: 18,
    photoName: 'pizzas/prosciutto.jpg',
    category: 'meat',
    image: '/img/prosciutto.jpg',
  },
];
